# docker-compose -f docker-compose.prod.yml up -d
services:
    movie-db-vue:
        container_name: movie-db-vue
        build:
            context: ./movie-db-vue
            dockerfile: Dockerfile_local
            target: production-stage
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./movie-db-vue:/app
    movie-db-core-api:
        container_name: movie-db-core-api
        build:
            context: ./movie-db-core-api
            target: 'production-stage'
        ports:
            - "3000:3000"
        restart: always
        volumes:
            - ./movie-db-core-api:/app