services:
    movie-db-vue:
        container_name: movie-db-vue
        build:
            context: ./movie-db-vue
            target: 'development-stage'
        ports:
            - "8080:8080"
        restart: always
        volumes:
            - ./movie-db-vue:/app
        command: /bin/sh -c "npm install && quasar dev"
    movie-db-core-api:
        container_name: movie-db-core-api
        build:
            context: ./movie-db-core-api
            target: 'development-stage'
        ports:
            - "3000:3000"
        restart: always
        volumes:
            - ./movie-db-core-api:/app