name: Build Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: echo $password | docker login -u $username --password-stdin

    - name: Build movie-db-vue image
      run: docker build ./movie-db-vue --platform linux/amd64 --file ./movie-db-vue/Dockerfile_local  --target production-stage  --tag sebvillebrun/movie-db-app:latest_vue

    - name: Push movie-db-vue image
      run: docker push sebvillebrun/movie-db-app:latest_vue

    - name: Build movie-db-core-api image
      run: docker build ./movie-db-core-api --platform linux/amd64 --file ./movie-db-core-api/Dockerfile --target production-stage --tag sebvillebrun/movie-db-app:latest_core-api

    - name: Push movie-db-core-api image
      run: docker push sebvillebrun/movie-db-app:latest_core-api
